- name: Ensure that the repository file exists
  template:
    src: atom.list.j2
    dest: /etc/apt/sources.list.d/atom.list

- name: Ensure the apt key exists
  apt_key:
    url: https://packagecloud.io/AtomEditor/atom/gpgkey

- name: Ensure atom is installed
  apt:
    name: atom
    state: present
    update_cache: yes

- name: Ensure atom packages are installed
  shell: "apm install {{ item }}"
  with_items:
    - activate-power-mode
    - aligner
    - aligner-javascript
    - atom-beautify
    - atom-ctags
    - atom-jinja2
    - atom-material-ui
    - atom-typeScript
    - autocomplete-ansible
    - autocomplete-xml
    - behat-atom
    - colorful-json
    - editorconfig
    - intentions
    - language-ansible
    - language-ini
    - linter
    - linter-ansible-linting
    - linter-js-yaml
