- name: Prepare environment variables
  hosts: all
  vars_prompt:
    - name: "user"
      prompt: "Who is the standard user?"
  tasks:
    - set_fact:
        user: "{{ user }}"

- name: Setup the machine
  remote_user: root
  hosts: all
  roles:
    - utilities
    - web_browsers
    - programming
